FROM tomcat
USER root
RUN set -ex; \
if ! type -f jar; then apk add --no-cache openjdk11-jdk; fi
USER tomcat
WORKDIR /webapps
ADD *.war ./
RUN set -ex; \
cd /webapps/ROOT; \
jar xf ../*.war

FROM tomcat
COPY --from=0 /webapps/ROOT /webapps/ROOT
